#!/bin/bash

for dir in [0][1-9];
do
    cd $dir
    Rscript fit\ g+b.R 
    cd ..
done

for dir in [1][0-2]
do
	cd $dir
	Rscript fit\ g+b.R
	cd ..
done

for dir in [2][0-3]
do
	cd $dir
	Rscript fit\ g+b.R
	cd ..
done
